CompraVenta.UI/Controllers/PrestamosController.cs
using CompraVenta.UI.Models;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CompraVenta.UI.Controllers

{
    [Authorize]
    public class PrestamosController : Controller
    {
      
        public const int ListaVacia = 0;
        // GET: Prestamos
        [Authorize]
        public ActionResult Index()
        {
            LogicaDeNegocio.CoordinadorDePrestamos.CoordinadorDePrestamos coordinadorDePrestamos;
            coordinadorDePrestamos = new LogicaDeNegocio.CoordinadorDePrestamos.CoordinadorDePrestamos();
            LogicaDeNegocio.CoordinadorDeAbonos.CoordinadorDeAbonos coordinadorDeAbonos;
            coordinadorDeAbonos = new LogicaDeNegocio.CoordinadorDeAbonos.CoordinadorDeAbonos();
            LogicaDeNegocio.CoordinadorDeClientes.CoordinadorDeClientes coordinadorDeClientes;
            coordinadorDeClientes = new LogicaDeNegocio.CoordinadorDeClientes.CoordinadorDeClientes();
            Convertidores.PrestamoConvertidor convertidorPrestamos = new Convertidores.PrestamoConvertidor();

            List<Model.Prestamos.Prestamos> laListaDeTodosLosPrestamos = coordinadorDePrestamos.ObtenerListaDeTodosLosPrestamos();

            List<Models.PrestamosModels> laListaDeModelsPrestamos = convertidorPrestamos.ObtenerListaConvertidaDePrestamos(laListaDeTodosLosPrestamos, coordinadorDePrestamos, coordinadorDeAbonos, coordinadorDeClientes);

            return View(laListaDeModelsPrestamos);
        }

        // GET: Prestamos/Details/5
        public ActionResult Details(int id)
        {
            LogicaDeNegocio.CoordinadorDeAbonos.CoordinadorDeAbonos coordinadorDeAbonos;
            coordinadorDeAbonos = new LogicaDeNegocio.CoordinadorDeAbonos.CoordinadorDeAbonos();
            LogicaDeNegocio.CoordinadorDePrestamos.CoordinadorDePrestamos coordinadorDePrestamos;
            coordinadorDePrestamos = new LogicaDeNegocio.CoordinadorDePrestamos.CoordinadorDePrestamos();
            LogicaDeNegocio.CoordinadorDeClientes.CoordinadorDeClientes coordinadorDeClientes;
            coordinadorDeClientes = new LogicaDeNegocio.CoordinadorDeClientes.CoordinadorDeClientes();
            Model.Prestamos.Prestamos prestamo = new Model.Prestamos.Prestamos();
            prestamo = coordinadorDePrestamos.ConsultarPrestamoPorId(id);

            Convertidores.PrestamoConvertidor convertidorDePrestamos = new Convertidores.PrestamoConvertidor();

            Models.PrestamosModels modelsPrestamo = convertidorDePrestamos.ObtenerConvertidorDetallePrestamoEspecifico(prestamo, coordinadorDePrestamos, coordinadorDeAbonos, coordinadorDeClientes);

            return View(modelsPrestamo);
        }

        public ActionResult ListarAbonos(List<Model.Abono.Abono> listaDeAbonos) {


            return View(listaDeAbonos);
        }

        // GET: Prestamos/Create
        public ActionResult Create()
        {
            Models.PrestamosModels PrestamoModels = new Models.PrestamosModels();
            LogicaDeNegocio.CoordinadorDePrestamos.CoordinadorDePrestamos coordinadorDePrestamos;
            coordinadorDePrestamos = new LogicaDeNegocio.CoordinadorDePrestamos.CoordinadorDePrestamos();
            PrestamoModels.laListaDePlazoDiasPrestamo = coordinadorDePrestamos.ObtenerPlazoDiasPrestamo();

            return View(PrestamoModels);
        }

        // POST: Prestamos/Create
        [HttpPost]
        public ActionResult Create(Models.PrestamosModels elPrestamo)
        {
            try
            {
                
                Convertidores.PrestamoConvertidor convertidorPrestamos = new Convertidores.PrestamoConvertidor();
                LogicaDeNegocio.CoordinadorDePrestamos.CoordinadorDePrestamos coordinadorDePrestamos;
                coordinadorDePrestamos = new LogicaDeNegocio.CoordinadorDePrestamos.CoordinadorDePrestamos();
                LogicaDeNegocio.CoordinadorDeClientes.CoordinadorDeClientes coordinadorDeClientes;
                coordinadorDeClientes = new LogicaDeNegocio.CoordinadorDeClientes.CoordinadorDeClientes();
              
                Model.Prestamos.Prestamos elNuevoPrestamo = new Model.Prestamos.Prestamos();
                var laListaDeClientesPorCedula = coordinadorDeClientes.ObtenerListaDeClientesPorCedula(elPrestamo.CedulaCliente);

                if (laListaDeClientesPorCedula.Count!=ListaVacia)
                {
                    elNuevoPrestamo = convertidorPrestamos.ObtenerConvertidorPrestamosPorPrestamoModelsCrear(elPrestamo, coordinadorDeClientes);
                   
                    string idUser = User.Identity.GetUserId();

                    elNuevoPrestamo.Id_AspNetUser = idUser;
                    coordinadorDePrestamos.AgregarUnPrestamo(elNuevoPrestamo);

                  

                        return RedirectToAction("Index");
                }
                else
                {
                    Models.PrestamosModels elPrestamoModels = new Models.PrestamosModels();
                    elPrestamoModels.laListaDePlazoDiasPrestamo = coordinadorDePrestamos.ObtenerPlazoDiasPrestamo();
                    ViewBag.Name = "Identificación del cliente no válida.";
                    return View(elPrestamoModels);
                }
            }
            catch
            {
                return View();
            }
        }

        // GET: Prestamos/Edit/5
        public ActionResult Edit(int id)
        {
            LogicaDeNegocio.CoordinadorDePrestamos.CoordinadorDePrestamos coordinadorDePrestamos;
            coordinadorDePrestamos = new LogicaDeNegocio.CoordinadorDePrestamos.CoordinadorDePrestamos();
            LogicaDeNegocio.CoordinadorDeClientes.CoordinadorDeClientes coordinadorDeClientes;
            coordinadorDeClientes = new LogicaDeNegocio.CoordinadorDeClientes.CoordinadorDeClientes();
            

            Model.Prestamos.Prestamos elPrestamo = new Model.Prestamos.Prestamos();
            elPrestamo = coordinadorDePrestamos.ConsultarPrestamoPorId(id);
            Model.Cliente.Clientes clienteDelPrestamo = coordinadorDeClientes.ConsultarClientePorId(elPrestamo.IdCliente);

            Convertidores.PrestamoConvertidor convertidorPrestamos = new Convertidores.PrestamoConvertidor();
            Models.PrestamosModels elPrestamoModels = convertidorPrestamos.ObtenerConvertidorPrestamoPorId(elPrestamo, coordinadorDePrestamos, clienteDelPrestamo);
            
            return View(elPrestamoModels);
        }

        // POST: Prestamos/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, Models.PrestamosModels elPrestamo)
        {
            try
            {
                
                Convertidores.PrestamoConvertidor convertidorPrestamos = new Convertidores.PrestamoConvertidor();

                LogicaDeNegocio.CoordinadorDePrestamos.CoordinadorDePrestamos coordinadorDePrestamos;
                coordinadorDePrestamos = new LogicaDeNegocio.CoordinadorDePrestamos.CoordinadorDePrestamos();

                LogicaDeNegocio.CoordinadorDeClientes.CoordinadorDeClientes coordinadorDeClientes;
                coordinadorDeClientes = new LogicaDeNegocio.CoordinadorDeClientes.CoordinadorDeClientes();
              

                Model.Prestamos.Prestamos elNuevoPrestamo = new Model.Prestamos.Prestamos();
                elNuevoPrestamo = coordinadorDePrestamos.ConsultarPrestamoPorId(id);
                var listaDeClientesPorCedula = coordinadorDeClientes.ObtenerListaDeClientesPorCedula(elPrestamo.CedulaCliente);



                var laListaDeClientesPorCedula = coordinadorDeClientes.ObtenerListaDeClientesPorCedula(elPrestamo.CedulaCliente);

                if (laListaDeClientesPorCedula.Count != ListaVacia)
                {
                    elNuevoPrestamo = convertidorPrestamos.ObtenerConvertidorPrestamosPorPrestamoModelsEditar(id,elPrestamo, listaDeClientesPorCedula, coordinadorDePrestamos);

                    coordinadorDePrestamos.EditarUnPrestamo(elNuevoPrestamo);

                    return RedirectToAction("Index");
                }
                else
                {
                    Models.PrestamosModels elPrestamoModels = new Models.PrestamosModels();
                    elPrestamoModels.laListaDePlazoDiasPrestamo = coordinadorDePrestamos.ObtenerPlazoDiasPrestamo();
                    ViewBag.Name = "Identificación del cliente no válida.";
                    return View(elPrestamoModels);
                }

            }
            catch
            {
                return View();
            }
        }

     
        public ActionResult ListaDePréstamosDelClientePorCedula(string cedulaABuscar)
        {
            List<Models.PrestamosModels> laListaDeModelsPrestamoPorCedula = new List<PrestamosModels>();
            string cedula = cedulaABuscar;

            LogicaDeNegocio.CoordinadorDeClientes.CoordinadorDeClientes coordinadorDeClientes;
            coordinadorDeClientes = new LogicaDeNegocio.CoordinadorDeClientes.CoordinadorDeClientes();
            LogicaDeNegocio.CoordinadorDePrestamos.CoordinadorDePrestamos coordinadorDePrestamos;
            coordinadorDePrestamos = new LogicaDeNegocio.CoordinadorDePrestamos.CoordinadorDePrestamos();
          
            List<Model.Cliente.Clientes> laListaDeLosClientesPorCedula = new List<Model.Cliente.Clientes>();

            LogicaDeNegocio.CoordinadorDeAbonos.CoordinadorDeAbonos coordinadorDeAbonos = new LogicaDeNegocio.CoordinadorDeAbonos.CoordinadorDeAbonos();
         
            List<Model.Prestamos.Prestamos> laListaDeTodosLosPrestamos = new List<Model.Prestamos.Prestamos>();

            List<Models.PrestamosModels> laListaDeModelsPrestamos = new List<Models.PrestamosModels>();


            laListaDeLosClientesPorCedula = coordinadorDeClientes.ObtenerListaDeClientesPorCedula(cedula);
            try
            {
                if (!string.IsNullOrEmpty(cedulaABuscar))
                {

CompraVenta.UI/Views/Prestamos/AbonarAlPrestamo.cshtml
@model CompraVenta.UI.Models.AbonoModels

@{
    ViewBag.Title = "AbonarAlPrestamo";
}

<h2>Abonar Al Préstamo</h2>

@ViewBag.Name
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            <br /> <label for="Monto">Monto:</label><br />
            <div class="col-md-10">
                @Html.EditorFor(model => model.Monto, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Monto, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Abonar" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Regresar a Buscar los Préstamos de un Cliente", "BuscarPrestamoCedulaCliente")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CompraVenta.UI/Views/Prestamos/AnularAbono.cshtml
@model CompraVenta.Model.Abono.Abono

@{
    ViewBag.Title = "AnularAbono";
}

<h2>¿Desea Anular el Abono?</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
   
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        

        <div class="form-group">
            <br /> <label for="Monto">Monto:</label><br />
            <div class="col-md-10">
                @Html.EditorFor(model => model.Monto, new { htmlAttributes = new { @class = "form-control" ,@disabled="true"} })
                @Html.ValidationMessageFor(model => model.Monto, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <br /> <label for="Fecha">Fecha de Ingreso:</label><br />
            <div class="col-md-10">
                @Html.EditorFor(model => model.Fecha, new { htmlAttributes = new { @class = "form-control", @disabled="true" } })
                @Html.ValidationMessageFor(model => model.Fecha, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Anular Abono" class="btn btn-danger" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Regresar a la Lista de Préstamos", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CompraVenta.UI/Views/Prestamos/BuscarPrestamoCedulaCliente.cshtml
@model CompraVenta.UI.Models.PrestamosModels

@{
    ViewBag.Title = "BuscarPrestamoCedulaCliente";
}

<h2>Buscar Préstamo por Cedula Cliente</h2>

@ViewBag.Name
@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
       

        <div class="form-group">
            <br /> <label for="CedulaCliente">Número de Cedula del Cliente:</label><br />
            <div class="col-md-10">
                @Html.EditorFor(model => model.CedulaCliente, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CedulaCliente, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Buscar" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Regresar a la Lista de Préstamos", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CompraVenta.UI/Views/Prestamos/Create.cshtml
@model CompraVenta.UI.Models.PrestamosModels

@{
    ViewBag.Title = "NuevoPrestamo";
}

<h2>Nuevo Préstamo</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        @ViewBag.Name
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            <br /> <label for="CedulaCliente">Identificación del Cliente:</label><br />
            <div class="col-md-10">
                @Html.EditorFor(model => model.CedulaCliente, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CedulaCliente, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <br /> <label for="CantidadPrestada">Cantidad de dinero prestada:</label><br />
            <div class="col-md-10">
                @Html.EditorFor(model => model.CantidadPrestada, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CantidadPrestada, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <br /> <label for="PlazoDiasPrestamo">Plazo del préstamo:</label><br />
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.PlazoDiasPrestamo,Model.ListaDePlazoDiasPrestamo)
                @Html.ValidationMessageFor(model => model.PlazoDiasPrestamo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <br /> <label for="DescripcionPrenda">Descripción de la prenda :</label><br />
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.DescripcionPrenda, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DescripcionPrenda, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Crear" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Regresar a la lista de Préstamos", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CompraVenta.UI/Views/Prestamos/Details.cshtml
@model CompraVenta.UI.Models.PrestamosModels

@{
    ViewBag.Title = "DetallePréstamos";
}

<h2>Detalles del Préstamo</h2>

<div>
 
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CedulaCliente)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CedulaCliente)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NombreClientes)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NombreClientes)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Fecha)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Fecha)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FechaVencimiento)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FechaVencimiento)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PlazoDiasPrestamo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PlazoDiasPrestamo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PorcentajeIntereses)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PorcentajeIntereses)%
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CantidadPrestada)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CantidadPrestada)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NombreUsuario)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NombreUsuario)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MontoPendienteDePago)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MontoPendienteDePago)
        </dd>

        <div> @Html.Partial("ListarAbonos",Model.AbonosDelPrestamo) </div>

    </dl>
</div>
<p>
   
    @Html.ActionLink("Regresar a la lista de Préstamo", "Index")
</p>

CompraVenta.UI/Views/Prestamos/DetalleAbonos.cshtml
@model CompraVenta.UI.Models.AbonoModels

@{
    ViewBag.Title = "DetalleAbonos";
}

<h2>Detalle Abono</h2>

<div>

    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.NombreClientes)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NombreClientes)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.FechaPrestamo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FechaPrestamo)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.FechaVencimiento)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FechaVencimiento)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.CantidadDias)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CantidadDias)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PorcentajeInteres)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PorcentajeInteres)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CantidadPrestada)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CantidadPrestada)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MontoPendientePago)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MontoPendientePago)
        </dd>

        <dt>
        Monto del abono
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Monto)
        </dd>

        <dt>
        Fecha del abono
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Fecha)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NombreUsuario)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NombreUsuario)
        </dd>
    </dl>
</div>
<p>
  
    @Html.ActionLink("Regresar a Buscar los Préstamos de un Cliente", "BuscarPrestamoCedulaCliente")
</p>

CompraVenta.UI/Views/Prestamos/ListarAbonos.cshtml
@model IEnumerable<CompraVenta.Model.Abono.Abono>

@{
    ViewBag.Title = "ListarAbonos";
}

<h5>Lista de Abonos</h5>


<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Monto)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Fecha)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Monto)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Fecha)
        </td>
    </tr>
}

</table>

CompraVenta.UI/Views/Prestamos/PrestamosPorCriterio.cshtml
@model IEnumerable<CompraVenta.UI.Models.PrestamosModels>

@{
    ViewBag.Title = "PrestamosPorCriterio";
}

<h3>Busqueda de prestamos</h3>


@using (Html.BeginForm("PrestamosPorCriterio", "Prestamos", FormMethod.Post))
{
    <fieldset>
        <legend>Criterios de búsqueda</legend>
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.Label("buscar", "Por cedula de cliente:")
        @Html.TextBox("cedula", null, new { id = "buscar" })
        
   
        @Html.Label("FechaDesde", "Fecha Desde:")
        <input type="date" name="fechaInicio" />
        @Html.Label("FechaHasta", "Fecha Hasta:")
        <input type="date" name="fechaHasta" />

        <br />
        @Html.Label("Estado", "Estados:")
        <div class="form-group">
            <select name="estado">
                <option value="--" selected>Seleccione un Estado...</option>
                <option value="Vencido">Vencido</option>
                <option value="NoVencido">No vencido</option>
            </select>
        </div>

        <input id="btnBuscarCliente" type="submit" value="Buscar" />
      
    </fieldset>
}
<br />
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.CedulaCliente)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Id)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Fecha)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FechaVencimiento)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CantidadPrestada)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PlazoDiasPrestamo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MontoPendienteDePago)
        </th>

        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.CedulaCliente)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Id)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Fecha)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FechaVencimiento)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CantidadPrestada)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PlazoDiasPrestamo)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.MontoPendienteDePago)
        </td>
    </tr>
}

</table>

CompraVenta.UI/Views/Prestamos/PrestamosPorCriterioCombinados.cshtml
@model IEnumerable<CompraVenta.UI.Models.PrestamosModels>

@{
    ViewBag.Title = "PrestamosPorCriterioCombinados";
}

<h2>Lista de Préstamos por Criterios Combinados</h2>


@using (Html.BeginForm("PrestamosPorCriterioCombinados", "Prestamos", FormMethod.Get))
{
    <fieldset>
        <input type="submit" value="Mostrar Todos" class="btn btn-primary" />
    </fieldset>
}
@using (Html.BeginForm("PrestamosPorCriterioCombinados", "Prestamos", FormMethod.Post))
{
    <fieldset>
        <legend>Criterios de búsqueda</legend>
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.Label("buscar", "Por cedula de cliente:")
        @Html.TextBox("cedula", null, new { id = "buscar" })


        @Html.Label("FechaDesde", "Fecha Desde:")
        <input type="date" name="fechaInicio" />
        @Html.Label("FechaHasta", "Fecha Hasta:")
        <input type="date" name="fechaHasta" />

        @Html.Label("Estado", "Estados:")
            <select name="estado">
                <option value="--" selected>Seleccione un Estado...</option>
                <option value="Vencido">Vencido</option>
                <option value="NoVencido">No vencido</option>
            </select>
        <hr />
<center><div class="form-group">
        <input type="submit" value="Buscar" class="btn btn-primary" />
</div></center>

    </fieldset>
}

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.CedulaCliente)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Id)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Fecha)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FechaVencimiento)
        </th>
        <th>
            Cantidad prestada
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PlazoDiasPrestamo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MontoPendienteDePago)
        </th>

        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.CedulaCliente)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Fecha)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FechaVencimiento)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CantidadPrestada)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PlazoDiasPrestamo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MontoPendienteDePago)
            </td>
        </tr>
                    }

</table>